---
title: "Lab 3 - Reducing Crime"
author: "Clayton G. Leach, Karl I. Siil, Timothy S. Slade"
date: "July 23, 2018"
output: 
  pdf_document: 
    latex_engine: xelatex
mainfont: 'Arial'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
```

# Introduction



```{r data_import}
crime_raw <- read_csv('../crime_v2.csv', 
                      col_types = cols(
                        prbconv = col_double()
                        ))
problems(crime_raw)
crime_raw[97, ]
```

```{r}

# Rows with no data
crime_na <- crime_raw %>%
  filter_all(any_vars(!is.na(.)))

# Row with one back tick
crime_na %>%
  filter_all(any_vars(is.na(.))) %>%
  select(which(!is.na(.)))
  
crime_na <- crime_na %>%
  filter_all(all_vars(!is.na(.)))
```

```{r}

crime_na %>%
  summary()
```

```{r}
crime_na %>%
  count(county) %>%
  filter(n > 1)

# county 193 is an exact duplicate 
crime_na %>%
  filter(county == 193)

crime_na <- crime_na %>%
  filter(!duplicated(.))

```

```{r}
# look at weird 'probability' variables.
crime_na %>%
  filter(!between(prbarr, 0, 1) | 
           !between(prbconv, 0, 1) |
           !between(prbpris, 0, 1))
           
```


```{r}

```
